#spring 项目名称,服务标识
spring:
  application:
    name: server
#服务器端口
server:
  port: 7001
#Eureka 注册服务器hostname
eureka:
  instance:
    hostname: loaclhost
  client:
    #是否注册给服务中心
    register-with-eureka: true
    #是否检索服务
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/